<?php
/*   __________________________________________________
    |  Obfuscated by YAK Pro - Php Obfuscator  2.0.14  |
    |              on 2024-09-11 13:11:17              |
    |    GitHub: https://github.com/pk-fr/yakpro-po    |
    |__________________________________________________|
*/
/*

*/
 defined("\x42\x41\x53\105\120\x41\x54\x48") or exit("\116\157\40\x64\151\162\145\143\164\40\x73\x63\162\x69\160\x74\x20\x61\143\x63\145\163\163\40\141\154\x6c\x6f\167\145\144"); class CI_Parser { public $l_delim = "\173"; public $r_delim = "\175"; protected $CI; public function __construct() { $this->CI =& get_instance(); log_message("\151\156\146\157", "\x50\x61\x72\163\x65\x72\40\103\x6c\x61\x73\163\x20\x49\156\151\164\151\141\154\x69\172\x65\x64"); } public function parse($template, $data, $return = FALSE) { $template = $this->CI->load->view($template, $data, TRUE); return $this->_parse($template, $data, $return); } public function parse_string($template, $data, $return = FALSE) { return $this->_parse($template, $data, $return); } protected function _parse($template, $data, $return = FALSE) { goto PUI_9; rU1ck: unset($data); goto Xrn7y; tGsk8: return $template; goto r6DWh; HUn2Z: $replace = array(); goto Lfbwp; gXw8B: if ($return === FALSE) { $this->CI->output->append_output($template); } goto tGsk8; Lfbwp: foreach ($data as $key => $val) { $replace = array_merge($replace, is_array($val) ? $this->_parse_pair($key, $val, $template) : $this->_parse_single($key, (string) $val, $template)); } goto rU1ck; Xrn7y: $template = strtr($template, $replace); goto gXw8B; PUI_9: if ($template === '') { return FALSE; } goto HUn2Z; r6DWh: } public function set_delimiters($l = "\x7b", $r = "\175") { $this->l_delim = $l; $this->r_delim = $r; } protected function _parse_single($key, $val, $string) { return array($this->l_delim . $key . $this->r_delim => (string) $val); } protected function _parse_pair($variable, $data, $string) { goto rwtd2; M4HIl: preg_match_all("\43" . preg_quote($this->l_delim . $variable . $this->r_delim) . "\x28\56\x2b\x3f\51" . preg_quote($this->l_delim . "\57" . $variable . $this->r_delim) . "\43\163", $string, $matches, PREG_SET_ORDER); goto pWnWP; RVTdl: return $replace; goto W8PR5; pWnWP: foreach ($matches as $match) { goto oW43V; kpfDJ: $replace[$match[0]] = $str; goto AgTrg; oW43V: $str = ''; goto qV1Gp; qV1Gp: foreach ($data as $row) { goto kCxvP; HvVQM: foreach ($row as $key => $val) { if (is_array($val)) { goto Dgpcd; pMYFP: if (!empty($pair)) { $temp = array_merge($temp, $pair); } goto iaHmp; Dgpcd: $pair = $this->_parse_pair($key, $val, $match[1]); goto pMYFP; iaHmp: continue; goto pXcVB; pXcVB: } $temp[$this->l_delim . $key . $this->r_delim] = $val; } goto b2rhE; b2rhE: $str .= strtr($match[1], $temp); goto rwRu7; kCxvP: $temp = array(); goto HvVQM; rwRu7: } goto kpfDJ; AgTrg: } goto RVTdl; rwtd2: $replace = array(); goto M4HIl; W8PR5: } }
